### ISSUE TITLE
JS2 Week 2 Feedback

### ISSUE THREAD

**Issue by orhantoy** [HouriaDanesh/hyf-homework#1]
@HouriaDanesh :v:

I've been reviewing your JS2 Week 2 homework. I think you have done a good job with the warmup exercises but seems like you got stuck with the hyfBay exercise.

## Warmup array exercises / Doubling of number

https://github.com/HouriaDanesh/hyf-homework/blob/cd461370b1e110536aa66fc2c47b50e0fb0ec70f/javascript/javascript2/week2/doubling.js#L10-L23

Good job on this. It works even though you have solved the exercise in a slightly different way than intended. Feedback:

- The exercise has a note saying "Rewrite the above program using `map` and `filter` don't forget to use arrow functions". You have not used arrow functions, so please look into rewriting the regular functions to arrow functions.
- Using chaining for this exercise would make the solution much more elegant. Hint: the overall shape would then be `numbers.filter([insert arrow function]).map([insert arrow function])`.

Feel free to ask questions in here related to my feedback and I would also appreciate if you give me an update when you have addressed the feedback.

## Warmup array exercises / Working with movies

Good job on these exercises 👍 

- In the first exercise you have the right solution but I think the const name could be more descriptive. The current name `shortTitle` sounds like it contains a single short title but in fact it is an array of movies with short titles. `shortTitledMovies` would be a more descriptive name here.
    https://github.com/HouriaDanesh/hyf-homework/blob/cd461370b1e110536aa66fc2c47b50e0fb0ec70f/javascript/javascript2/week2/movies/main.js#L4
- Similar to my first comment, this const could have been named `longTitledMovies`.
    https://github.com/HouriaDanesh/hyf-homework/blob/cd461370b1e110536aa66fc2c47b50e0fb0ec70f/javascript/javascript2/week2/movies/main.js#L11
- You almost have the right solution for exercise 3, you are missing the counting part. We want you to count the movies from the 80s, but you are instead returning a list of the movies from the 80s.
    https://github.com/HouriaDanesh/hyf-homework/blob/cd461370b1e110536aa66fc2c47b50e0fb0ec70f/javascript/javascript2/week2/movies/main.js#L17-L18
- You almost have the right solution for exercise 4. Hint: you should not return `movies` in the function.
    https://github.com/HouriaDanesh/hyf-homework/blob/cd461370b1e110536aa66fc2c47b50e0fb0ec70f/javascript/javascript2/week2/movies/main.js#L24-L39
- Nice solution to the exercise 5 👍
- Your solution for exercise 6 fails when trying to run it. Seems like you are trying 2 different things in `keywordMovie` and `matchTitle` but you should try combining these, if that makes sense. Feel free to ask questions in here if you want more guidance on this.
    https://github.com/HouriaDanesh/hyf-homework/blob/cd461370b1e110536aa66fc2c47b50e0fb0ec70f/javascript/javascript2/week2/movies/main.js#L52-L63
- You haven't done exercise 7 it seems like. Try to get exercise 6 done first and then look into 7 afterwards. Feel free to ask questions about exercise 7 in here as well.

One general comment with the exercises here is that all of them could probably be rewritten to use arrow functions. I don't think it is required for these exercises though, so it is not a big deal.
And lastly, I would recommend using some linting tools that can help format your code to look nicer and more consistent.

## hyfBay - get the okay'est products here - continued

Seems like you have attempted to add searching capabilities but it doesn't seem to work. I'm not sure what to give feedback on here so I think the easiest is that you ask questions in here on the things you need help with.

**Comment by orhantoy** [comment]
@HouriaDanesh Update: I just added feedback for "Warmup array exercises / Working with movies".

**Comment by orhantoy** [comment]
@HouriaDanesh Update: I've just taken a closer look at the hyfBay exercise and given a bit of feedback.

**Comment by HouriaDanesh** [comment]
many thanks dear Orhan for you nice review i am so appreciate it :)

**Comment by orhantoy** [comment]
@HouriaDanesh Just a reminder to address the feedback :v:

**Comment by chklueter** [comment]
Whoa, great feedback and effiort @orhantoy !!
